"""added unique constraint to booking

Revision ID: 8b161a2b5c3c
Revises: 
Create Date: 2025-11-20 20:56:43.986346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b161a2b5c3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_slot', ['court_id', 'booking_date', 'start_time', 'end_time'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint('unique_slot', type_='unique')

    # ### end Alembic commands ###
