// data.js

export const courtsData = [{
        id: "1",
        name: "Downtown Tennis Court",
        location: "123 Main St, Downtown",
        owner_name: "John Smith",
        hourly_rate: 50,
        type: "Tennis",
        status: "approved",
        image_url: "/outdoor-tennis-court.png",
    },
    {
        id: "2",
        name: "Basketball Arena",
        location: "456 Sports Ave, Midtown",
        owner_name: "Sarah Johnson",
        hourly_rate: 75,
        type: "Basketball",
        status: "approved",
        image_url: "/outdoor-basketball-court.png",
    },
    {
        id: "3",
        name: "Badminton Court",
        location: "789 Fitness Blvd, Uptown",
        owner_name: "Mike Chen",
        hourly_rate: 40,
        type: "Badminton",
        status: "approved",
        image_url: "/badminton-court.png",
    },
    {
        id: "4",
        name: "Volleyball Complex",
        location: "321 Beach St, Coastal",
        owner_name: "Emma Wilson",
        hourly_rate: 60,
        type: "Volleyball",
        status: "approved",
        image_url: "/outdoor-volleyball-court.png",
    },
];

export const pendingCourtsData = [{
        id: "5",
        name: "Premium Squash Courts",
        location: "555 Elite Drive, City Center",
        owner_name: "Alex Rodriguez",
        hourly_rate: 85,
        type: "Squash",
        status: "pending",
        image_url: "/squash-court.jpg",
    },
    {
        id: "6",
        name: "Table Tennis Hub",
        location: "666 Recreation Ln, Suburbs",
        owner_name: "Lisa Park",
        hourly_rate: 35,
        type: "Table Tennis",
        status: "pending",
        image_url: "/table-tennis-match.png",
    },
    {
        id: "7",
        name: "Pickleball Paradise",
        location: "777 Community Way, East Side",
        owner_name: "David Brown",
        hourly_rate: 45,
        type: "Pickleball",
        status: "pending",
        image_url: "/pickleball-court.jpg",
    },
];

export const usersData = [{
        id: "u1",
        full_name: "John Smith",
        email: "john.smith@example.com",
        role: "owner",
        phone: "+1 (555) 123-4567",
    },
    {
        id: "u2",
        full_name: "Sarah Johnson",
        email: "sarah.johnson@example.com",
        role: "owner",
        phone: "+1 (555) 234-5678",
    },
    {
        id: "u3",
        full_name: "Mike Chen",
        email: "mike.chen@example.com",
        role: "owner",
        phone: "+1 (555) 345-6789",
    },
    {
        id: "u4",
        full_name: "Emma Wilson",
        email: "emma.wilson@example.com",
        role: "owner",
        phone: "+1 (555) 456-7890",
    },
    {
        id: "u5",
        full_name: "Alex Rodriguez",
        email: "alex.rodriguez@example.com",
        role: "user",
        phone: "+1 (555) 567-8901",
    },
    {
        id: "u6",
        full_name: "Lisa Park",
        email: "lisa.park@example.com",
        role: "user",
        phone: "+1 (555) 678-9012",
    },
    {
        id: "u7",
        full_name: "David Brown",
        email: "david.brown@example.com",
        role: "user",
        phone: "+1 (555) 789-0123",
    },
    {
        id: "u8",
        full_name: "Jennifer Lee",
        email: "jennifer.lee@example.com",
        role: "admin",
        phone: "+1 (555) 890-1234",
    },
];